version: '3'
services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  curl:
    image: curlimages/curl
    command: ["tail", "-f", "/dev/null"]

  nestjs-app:
    image: nest-app
    build: ./LatencyTracker
    ports:
      - '2000:2000'
      - '8001:8001'
    depends_on:
      - mysql
      - curl
    env_file:
      - .env

  react-app:
    image: react-app
    build: ./LatencyTracker-ui
    ports:
      - '3000:3000'

volumes:
  mysql_data:
